### ISSUE TITLE
Grpc service mock

### ISSUE THREAD

**Issue by juchaosong** [micronaut-projects/micronaut-grpc#105]
How dow I mock grpc service like https://github.com/grpc/grpc-java/blob/master/examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
