### ISSUE TITLE
Support for disabling gRPC server

### ISSUE THREAD

**Issue by racevedoo** [micronaut-projects/micronaut-grpc#112]
Hi,

Is there any way to disable a gRPC server to start? In my case, I am using micronaut-grpc for grpc clients only, and it is starting a grpc server unnecessarily.

Shouldn't we have a `grpc.server.enabled` config?

Thanks!

**Comment by racevedoo** [comment]
If the `grpc.server.enabled` config is possible, I can create a PR

**Comment by gaetancollaud** [comment]
> In my case, I am using micronaut-grpc for grpc clients only, and it is starting a grpc server unnecessarily.

Same here

**Comment by graemerocher** [comment]
My suggestion rather than disabling is to split the project into 2 modules a client and a server

**Comment by racevedoo** [comment]
> My suggestion rather than disabling is to split the project into 2 modules a client and a server
Looks good, any idea of how we can take this forward?

**Comment by graemerocher** [comment]
PRs are of course welcome, otherwise hopefully I will get round to it soon.

**Comment by bidorffOL** [comment]
Actually it would be usefull to be able to disable the gRPC server even when not using the gRPC client: I perform a lot of unit tests related to my database and starting a gRPC server when running those is kinda of useless (and time consuming). It would be great to be able to disable the gRPC server in specific environments through `grpc.server.enabled`.

I'll take a look a the code and try to provide a PR if I can.
