### ISSUE TITLE
Micronaut fails to create GrpcNamedManagedChannelConfiguration.class due to multiple executor services

### ISSUE THREAD

**Issue by jntakpe** [micronaut-projects/micronaut-grpc#170]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Using micronaut launch simply create a gRPC application
2. In `application.yml` file configure a gRPC channel as follow:
```yml
grpc:
  channels:
    foo:
      address: http://localhost:8081
      plaintext: true
```
3. Try to inject the configured channel:
```kotlin
@Factory
class GrpcConfig {
    @Singleton
    fun userStub(@GrpcChannel("foo") channel: ManagedChannel): ExecutorServiceGrpc.ExecutorServiceBlockingStub {
        return ExecutorServiceGrpc.newBlockingStub(channel)
    }
}
```
4. Try to inject the stub:
```kotlin
@Singleton
class BarService(private val fooStub: ExecutorServiceGrpc.ExecutorServiceBlockingStub): ExecutorServiceGrpc.ExecutorServiceImplBase() {
    override fun send(request: ExecutorRequest, responseObserver: StreamObserver<ExecutorReply>) {
        fooStub.toString()
        responseObserver.onCompleted()
    }
}
```

### Expected Behaviour

The channel (`@GrpcChannel("foo") channel: ManagedChannel`) should be configured and injected.

### Actual Behaviour

The application fails to start with the following message:

```
Message: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
Path Taken: new GrpcNamedManagedChannelConfiguration(String name,Environment env,[ExecutorService executorService])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [executorService] of class: io.micronaut.grpc.channels.GrpcNamedManagedChannelConfiguration

Message: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
Path Taken: new GrpcNamedManagedChannelConfiguration(String name,Environment env,[ExecutorService executorService])
```

### Environment Information

- **Operating System**: OS X Mojave : 10.14.6
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11.0.7 hotspot

### Example Application

[simple reproducer](https://github.com/jntakpe/grpc-conf-issue)

**Comment by graemerocher** [comment]
Looks like https://github.com/micronaut-projects/micronaut-grpc/blob/master/grpc-client-runtime/src/main/java/io/micronaut/grpc/channels/GrpcNamedManagedChannelConfiguration.java#L45

Should have `@Named(TaskExecutors.IO)` on the parameter and probably `GrpcDefaultManagedChannelConfiguration` as well. 

Would you like to send a PR?

**Comment by jntakpe** [comment]
@graemerocher [here](https://github.com/micronaut-projects/micronaut-grpc/pull/171) is the PR, unfortunately I wasn't able to reproduce the bug in the unit tests, I have no idea why. I tried to create new ExecutorService bean manually and to create custom grpc channel but original tests didn't failed so I just kept them tests as is
