### ISSUE TITLE
Service Discovery - Service name not known until runtime

### ISSUE THREAD

**Issue by swarren-sumglobal** [micronaut-projects/micronaut-grpc#185]
As long as I know the service name ahead of time (e.g. @GrpcChannel("greeter")), all is well, but I don't see a way to handle the scenario where the app doesn't get the service name until runtime.

Is there a way to utilize Micronaut service discovery to discover a service whose name is not known by the application until runtime? 

Thanks!

**Comment by ilopmar** [comment]
Please ask questions on Gitter: https://gitter.im/micronautfw
