### ISSUE TITLE
ByteBufToProtoMessageConverter does not respect @Consumes annotation

### ISSUE THREAD

**Issue by newink** [micronaut-projects/micronaut-grpc#216]
ByteBufToProtoMessageConverter throws `IllegalStateException`, but `TypeConverter::convert` method javadoc says that `* @return The converted type or empty if the conversion is not possible`
https://github.com/micronaut-projects/micronaut-grpc/blob/a18bed1aa2e19a57ee3e4be317f3ce11b545b9eb/protobuff-support/src/main/java/io/micronaut/protobuf/convert/ByteBufToProtoMessageConverter.java#L62

This behavior makes impossible to deserialize body for websocket handlers by using `@Consumes` annotation with Protobuf generated java classes. `AbstractNettyWebSocketHandler` tries to convert object using conversion service which determines converter by argument type. Converter tries to call `ByteBufToProtoMessageConverter` and fails (body is json string). `ByteBufToProtoMessageConverter` should return `Optional.empty()` here and then `AbstractNettyWebSocketHandler` will read `MediaType` from `@Consumes` annotation and deserialize with proper converter.

**Comment by graemerocher** [comment]
Does look like a bug, would you consider submitting a PR?

**Comment by newink** [comment]
@graemerocher done
