### ISSUE TITLE
Add a health check for the grpc-server

### ISSUE THREAD

**Issue by moeHaydar** [micronaut-projects/micronaut-grpc#236]
Add a grpc health check with the following configuration: 
`grpc.server.health.enabled`

By default the value will be true.

Feature will require
`io.micronaut:micronaut-management`

**Comment by moeHaydar** [comment]
I have the code for this,

Just can't produce a PR for this.

What is the procedure ?

**Comment by ilopmar** [comment]
This was done in https://github.com/micronaut-projects/micronaut-grpc/pull/237

**Comment by noam-alchemy** [comment]
Is there a way to expose a grpc health check on the server?
