### ISSUE TITLE
Separate health + tracing into individual modules

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-grpc#265]
The server tracing and health, and client tracing, should not be part of the core runtime. Tracing introduces unwanted coupling, since there's no telling that the user would want to use OpenTracing. Also, OpenTracing has been superceded by OpenTelemetry.
As for gRPC health service, it should be separate too and only enabled if `grpc.server.health.enabled=true`.

**Comment by graemerocher** [comment]
Tracing is already separated in that it it is only activated when the necessary dependencies are on the classpath https://github.com/micronaut-projects/micronaut-grpc/blob/master/grpc-client-runtime/src/main/java/io/micronaut/grpc/client/tracing/package-info.java#L20

Health checks are debatable and can be disabled already if not needed

**Comment by asarkar** [comment]
@graemerocher 
Dependency detection is risky because those classes may be present on the classpath without the user's explicit knowledge brought in as transitive dependencies. IMO, cross-cutting concerns like should be opt-in, not opt-out. If someone wants tracing and health check, they can easily include `micronaut-grpc-tracing` and `micronaut-grpc-health` (representative names), and activate either by annotation (`EnableGrpcTracing`) or by external property (`micronaut.grpc.tracing.enable=true`).

I think one thing that should differentiate Micronaut from something like Spring Boot is that it doesn't try to do black magic without the user's knowledge, and doesn't take a kitchen sink approach. Lean and small libraries are preferred over "autoconfigure everything".

**Comment by yibo-long** [comment]
+1 with @asarkar 

We spent quite some time to figure out why our compile/runtime doesn't have opentracing dependency but it's still creating micronaut grpc's opentracing span in DataDog as duplicate of DataDog's own, and finally came to realize that injecting DataDog java agent also added opentracing available into the classpath.
