### ISSUE TITLE
java.nio.channels.UnresolvedAddressException when using gRPC clients configured with micronaut-grpc

### ISSUE THREAD

**Issue by jmpalomar** [micronaut-projects/micronaut-grpc#270]
When using gRPC clients configured with micronaut-grpc sometimes everything works and sometimes you get  `java.nio.channels.UnresolvedAddressException`. 

After some checking, I found the issue is because there are two different converters for `SocketAddress` with different behavior. 

Converter provided by micronaut-http creates unresolved `SocketAddress` instances:
````
        conversionService.addConverter(
                CharSequence.class,
                SocketAddress.class,
                (object, targetType, context) -> {
                    String[] parts = object.toString().split(":");
                    if (parts.length == 2) {
                        int port = Integer.parseInt(parts[1]);
                        return Optional.of(InetSocketAddress.createUnresolved(parts[0], port));
                    } else {
                        return Optional.empty();
                    }
                }
        );
````

Converter provided by micronaut-grpc-client-runtime creates resolved `SocketAddress` instances:
````
        conversionService.addConverter(CharSequence.class, SocketAddress.class, charSequence -> {
            String[] parts = charSequence.toString().split(":");
            if (parts.length == 2) {
                int port = Integer.parseInt(parts[1]);
                return new InetSocketAddress(parts[0], port);
            } else {
                return null;
            }
        });
````

Depending on the order those converters are registered gRPC clients will work or will fail throwing `java.nio.channels.UnresolvedAddressException`. 

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run example application several times
2. Check log output

### Expected Behaviour

gRPC clients work and do not throw `java.nio.channels.UnresolvedAddressException` if properly configured.

### Actual Behaviour

gRPC clients sometimes work but other times throw `java.nio.channels.UnresolvedAddressException` and the only solution is to restart the application and hope for converters to be registered in proper order.

### Environment Information

- **Operating System**: Mac OS X Big Sur
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11.0.9

### Example Application

https://github.com/jmpalomar/micronaut-grpc-unresolved-issue

This is an small application that simply converts property `grpc.channels.test.address` value to `SocketAddress`. When executing the application several times you will see sometimes the address is resolved but others not:
````
% gradle run

> Task :run
08:02:02.876 [main] INFO  io.energiaplus.micronaut.Application - Optional[localhost/127.0.0.1:8080]

BUILD SUCCESSFUL in 4s
3 actionable tasks: 2 executed, 1 up-to-date
% gradle run

> Task :run
08:02:09.331 [main] INFO  io.energiaplus.micronaut.Application - Optional[localhost:8080]

BUILD SUCCESSFUL in 5s
3 actionable tasks: 1 executed, 2 up-to-date
````

**Comment by senthil-yolabs** [comment]
This bug which we are also experiencing is causing us to not be able to upgrade from our version of MN. I don't mind helping out, but I'm a little unclear why for HTTP you can live with an unresolved address, yet gRPC wants a resolved version of it.

**Comment by graemerocher** [comment]
submitted PR

**Comment by senthil-yolabs** [comment]
Thanks for that quick turnaround!
