### ISSUE TITLE
loadbalancing support

### ISSUE THREAD

**Issue by iamdobi** [micronaut-projects/micronaut-grpc#31]
Is there any mechanism to support grpc loadbalancing?

I tried 3 grpc server (greeter-service), and 1 grpc client with Consul discovery.

See Below.

<img width="426" alt="greeter-service" src="https://user-images.githubusercontent.com/15792655/62911722-53deed80-bdc0-11e9-93b1-05dc2c3af734.png">

Service discovery itself was worked as expected.
But once client connected to one specific server, following requests were handled only that server, until I shutdown that server.

I turned off service discovery cache (mictonaut.caches.discovery-client.enabled: false), and set server keep-alive-time to 3s (grpc.server.keep-alive-time: 3s).

When it comes to REST API servers with @Client annotation, it acted with round-robin strategy.

Happy Micronauting!

**Comment by graemerocher** [comment]
The load balancing integration can be found here https://github.com/micronaut-projects/micronaut-grpc/blob/master/grpc-runtime/src/main/java/io/micronaut/grpc/discovery/GrpcNameResolverProvider.java#L102

You have to set `grpc.client.discovery.enabled` to `true`
