### ISSUE TITLE
GRPC server doesn't call awaitTermination on shutdown

### ISSUE THREAD

**Issue by pratik-brex** [micronaut-projects/micronaut-grpc#313]
The gRPC server offers a `https://grpc.github.io/grpc-java/javadoc/io/grpc/Server.html#awaitTermination--` to ensure that the server is properly terminated. Currently only `shutdownNow` is being invoked: https://github.com/micronaut-projects/micronaut-grpc/blob/df8a3301d9c85e47811d76eea255403989e32480/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcEmbeddedServer.java#L201

It'd be great to add either an option or change default behavior to call `awaitTermination` with some configurable timeout.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by kow3ns** [comment]
Here is a PR that addresses the issue we found https://github.com/micronaut-projects/micronaut-grpc/pull/314

**Comment by graemerocher** [comment]
Thanks for the contribution!
