### ISSUE TITLE
Client cancelation of streaming request

### ISSUE THREAD

**Issue by toojuu** [micronaut-projects/micronaut-grpc#327]
Hello!

I can mention I'm fairly new to gRPC overall so I might have missed something. But, I’m looking into how to cancel a gRPC stream request, normally if I understand the gRPC documentation correctly that would be done on the channel context or converting the `StreamObserver` to a `ClientCallStreamObserver`.
Neither solution would work right now as far as I can see, as I do not have access to the context and `ClientCallStreamObserver` is not even part of micronaut gRPC.

I did find that you can throw and exception in the client which will cancel the stream, but that seems like bad control flow and I think it would be better to have a more framework supported solution.

**Comment by graemerocher** [comment]
more of a question and about gRPC not specifically Micronaut
