### ISSUE TITLE
Allow creating named clients for all configured channels

### ISSUE THREAD

**Issue by pfyod** [micronaut-projects/micronaut-grpc#329]
In our setup, we have multiple services that provide the same interface. e.g.
```yaml
grpc:
  channels:
    service-a:
      address: ...
    service-b:
      address: ...
```

There seems to be no way to create a factory that produces named stubs without compile time knowledge about which channels to create stubs for, due to internal use of parameterized factories and a custom scope that handles `@GrpcChannel`.

Ideally, something like this should be possible:
```java
@Factory
class NamedStubFactory {
   @EachBean(ManagedChannel.class)
   public CommonInterfaceStub stub(ManagedChannel channel) {
     return CommonInterfaceGrpc.newStub(channel);
   }
}
```
and then somewhere else
```java
@Inject
@Named("service-a")
```

This does not work, because `ManagedChannel` beans are not `@Named`. Maybe there's an alternative solution?

**Comment by cnadiminti** [comment]
@pfyod In a somewhat similar scenario, we are building a map of channel-name and stub and injecting the map into the stub consumer bean. Hope this helps. 
```java
    @Singleton
    @Named("ChannelNameClientStubMap")
    public Map<String, CommonInterfaceStub> buildChannelNameClientStubMap(List<GrpcNamedManagedChannelConfiguration> channelConfigurations) {
        return channelConfigurations.stream()
                .collect(Collectors.toUnmodifiableMap(
                        GrpcManagedChannelConfiguration::getName,
                        channelConfig -> CommonInterfaceGrpc.newStub(channelConfig.getChannelBuilder().build())));
    }
```

**Comment by milanspre** [comment]
@pfyod `GrpcNamedManagedChannelConfiguration` beans are named, since they use EachProperty.
That means beans created with `EachBean` will be named too. 
To make `ManagedChannel` beans, you could add the following snippet:
```java
    @EachBean(GrpcNamedManagedChannelConfiguration.class)
    public ManagedChannel exampleManagedChannel(GrpcNamedManagedChannelConfiguration channelConfig,
                                                List<ClientInterceptor> interceptors
    ) {
        return channelConfig.getChannelBuilder().intercept(interceptors).build();
    }
```

and then your snippet should work, including injection part.
