### ISSUE TITLE
Grpc Server can't start on Amazon ECS

### ISSUE THREAD

**Issue by jmc-elodie** [micronaut-projects/micronaut-grpc#350]
I am trying to use micronaut (v2.4.0) with Kotlin (v1.5.0) on AWS. In AWS I have setup an Elastic Container Service cluster using Fargate (AWS hosts the server cluster, not me). 

My server fails to start because with an error `java.net.SocketException` originiating from `io.micronaut.discovery.cloud.ComputeInstanceMetadataResolverUtils.readMetadataUrl(...)` and exits causing the task to fail.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a hello world gRPC project with micronaut-grpc v2.4.0 (I also reproed this on 2.2 and 2.3 and I believe the issue exists in every version)
2. Create a docker container using the `dockerBuild` gradle task
3. In AWS create an ECR repo for the container and an ECS cluster backed with Fargate
4. docker push your container to the ECR repo
5. Create a task definition in ECS using your container. Configure a log group for your task here.
e.g. like this
```
{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::xxxxxx:role/execRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "environmentFiles": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "frontend-app",
          "awslogs-region": "us-west-1",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "portMappings": [
        {
          "hostPort": 50051,
          "protocol": "tcp",
          "containerPort": 50051
        },
        {
          "hostPort": 8080,
          "protocol": "tcp",
          "containerPort": 8080
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "956515734762.dkr.ecr.us-west-1.amazonaws.com/elodie/skies-frontend-app:0.1-TEST2",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "app"
    }
  ],
  "placementConstraints": [],
  "memory": "2048",
  "taskRoleArn": "arn:aws:iam::xxxxx:role/taskRole",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-west-1:xxxxxxx:task-definition/service:8",
  "family": "service",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "revision": 8,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}
```

6. Create a service in ECS to run your task definition with a count of 1 instance

### Expected Behaviour

The service should run and the greet endpoint should be reachable and callable

### Actual Behaviour

Your ECS task fails to start because the primary container exited in error
Look at the logs for the task to see a similar stacktrace to below

Stacktrace: https://gist.github.com/jmc-elodie/82037e7bb12a7376ca4085b14a3b7a52

### Environment Information

- **Operating System**: Alpine linux in Docker on ECS Fargate
- **Micronaut Version:** 2.4.0
- **JDK Version:** 16

### Example Application

https://github.com/jmc-elodie/micronaut-grpc-repro

You will need to change the image in the gradle file to use your own ECR repo

**Comment by jmc-elodie** [comment]
One question I have here is why does micronaut discovery try and reinvent the wheel on detecting and getting the AWS metadata vs letting the AWS SDK do it? I think this happens in GRPC (and not a normal HTTP controller) because micronaut grpc explicitly calls micronaut discovery on server startup `GrpcEmbeddedServer:166`. Can I just disable that?

**Comment by jmc-elodie** [comment]
It looks like I am able to work around this by adding this to my config but I don't have a good understanding of what the sideffects will be:

```
micronaut:
  application:
    ec2:
      metadata:
        enabled: false
```

**Comment by graemerocher** [comment]
not an issue in latest releases of Micronaut where the compute instance resolver for AWS is not part of core
