### ISSUE TITLE
Integration with Security

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-grpc#361]
For now, security seems to be completely up to the developer. It does not really feel like writing a Micronaut service where we usually just extend the `AuthenticationProvider` and that's it.

It would be nice if `micronaut-grpc` would also "just apply" the `micronaut-security` stuff. But I guess `micronaut-security` is somewhat closely coupled to the HTTP calls (e.g. the `AuthenticationProvider.authenticate()` wants a `HttpRequest`) and this would need some rewrite.

**Comment by graemerocher** [comment]
Duplicates #164
