### ISSUE TITLE
Expose a gRPC Health Check for grpc-server

### ISSUE THREAD

**Issue by noam-alchemy** [micronaut-projects/micronaut-grpc#407]
### Feature description

The current healthcheck returns a REST response on `/health`. There are several situations in which a grpc-server should return a gRPC response (as an example, AWS ALBs require gRPC health checks for gRPC target groups).

There is a well defined standard defined here: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

It should be implemented and enabled via `grpc.server.health.enabled-grpc`, after which, the following API should be available on the server:

```
service Health {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse);

  rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
}
```

**Comment by JasonTypesCodes** [comment]
@timyates is doing some planning around this and will check back in here with any questions / details

**Comment by noam-alchemy** [comment]
Sounds good, Thanks Jason! cc @stevenzyang.

**Comment by timyates** [comment]
Hi @noam-alchemy, 👋😀

I've [come up with a PR](https://github.com/micronaut-projects/micronaut-grpc/pull/516) that hopefully fulfils this requirement. Can you take a look, and let me know if I've missed anything?

Thanks!
