### ISSUE TITLE
Can't upgrade to GRPC 1.45.0

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-grpc#420]
### Actual Behaviour

Problem in `grpc-client-runtime` module tests. When I start it I see this:
```

> Task :grpc-client-runtime:test

io.micronaut.grpc.GrpcNamedChannelSpec test named client PASSED (1.5s)
io.micronaut.grpc.GrpcNamedChannelSpec test named client - eager init PASSED
io.micronaut.grpc.HelloWordGrpcSpec test hello world grpc PASSED

  19:40:42.592 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
  19:40:42.593 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
  19:40:42.598 [Test worker] INFO  i.m.context.DefaultBeanContext - Reading bootstrap environment configuration
```

At this point, the test freezes. This problem with any GRPC version upper 1.39.0.

### Steps To Reproduce

Try to set `grpcVersion=1.45.0` in gradle.properties and build project locally

### Environment Information

Win10
JDK 17

### Version

3.1.3

**Comment by altro3** [comment]
@graemerocher @ilopmar Hi! I think we need your help in solving this problem. Version 1.39.0 was released back in June 2021, I think it is already becoming a problem that it is not possible to correctly update the entire package to use the modern version 1.45.0

**Comment by graemerocher** [comment]
Will look into it next week

**Comment by graemerocher** [comment]
I submitted a PR

**Comment by altro3** [comment]
Thanks! :-)
