### ISSUE TITLE
gRPC server doesn't shutdown gracefully

### ISSUE THREAD

**Issue by dustin-johnson** [micronaut-projects/micronaut-grpc#454]
[GrpcServerConfiguration has an awaitTermination configuration](https://github.com/micronaut-projects/micronaut-grpc/blob/a03f6ad05b48bf7682c41cdab57fe32e160937f3/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerConfiguration.java#L69) that defaults to 30 seconds. This configuration is supposed to give the gRPC services time to respond to any in-progress requests before termination. Unfortunately, the GrpcEmbeddedServer doesn't honor this, instead [calling shutdownNow() on the gRPC server](https://github.com/micronaut-projects/micronaut-grpc/blob/a03f6ad05b48bf7682c41cdab57fe32e160937f3/grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcEmbeddedServer.java#L206) instead of shutdown(), as it should.

**Comment by graemerocher** [comment]
Thanks for the contribution!
