### ISSUE TITLE
Referencing channel specific configuration not working

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-grpc#51]
The documentation mentions a way to provide channel specific configuration in `application.yml`. But if I try to access such an entry as described (like `@GrpcChannel("greeter")`) I only get `UknownHostException: greeter`. Has the syntax for the feature or the configuration entries changed?

**Comment by graemerocher** [comment]
Did you provide the configuration as per https://micronaut-projects.github.io/micronaut-grpc/latest/guide/#client ?

**Comment by esocode** [comment]
Yes, that is the example I followed. But using the channel name in @GrpcChannel causes the exception. Using an explicit URL (either directly or from the config) works without problems.

**Comment by graemerocher** [comment]
Will take a look. Thanks

**Comment by paulolieuthier** [comment]
Same problem here, tested on 1.2.5, 1.2.6, 1.2.7 and 1.2.8.

**Comment by paulolieuthier** [comment]
@graemerocher maybe you can point me where to look?

**Comment by graemerocher** [comment]
@paulolieuthier The custom scope is what looks these channels up https://github.com/micronaut-projects/micronaut-grpc/blob/master/grpc-runtime/src/main/java/io/micronaut/grpc/channels/GrpcChannelScope.java#L76

Curios that is failing as we have a test that tests this https://github.com/micronaut-projects/micronaut-grpc/blob/master/grpc-runtime/src/test/groovy/io/micronaut/grpc/discovery/GrpcServiceDiscoverySpec.groovy#L110

But maybe this is another case

**Comment by paulolieuthier** [comment]
The test case you linked enables service discovery, which should not be necessary, according to the docs. After enabling it, I see a different error: `io.micronaut.discovery.exceptions.NoAvailableServiceException: No available services for ID`.
