### ISSUE TITLE
Feature Request: avro-support (I can code it - just need a gradle project to get me going)

### ISSUE THREAD

**Issue by krickert** [micronaut-projects/micronaut-grpc#605]
### Feature description

I'm working on an avro environment.  I'm planning to try out the micronaut gpc plugin and saw how little code / how similar a plugin to get avro support would me.

I'd be willing to add it to the 3.x branch and 4.x branches (or whatever path we would do to get it added) - my only hold up: I'm totally used to workin' in maven and not really familiar with gradle.  

I would be willing to get a new branch going to implement this feature if someone can branch it and setup a skeleton project identical to the RPC one - except to include the avro-tools and avro dependences. (unless what I"m asking for is a major pain, then I'll just drudge through it.)

But looking at the code, I'd try to make identical tests for the avro support.

**Comment by graemerocher** [comment]
you wish to create a whole new project for Avro is that correct?

**Comment by krickert** [comment]
The grpc project has a module called "protobuf-support" - I would just want a branch with the same dependencies minus the Google protocol buff portion but have the avro and avro-tools dependencies added.  I figure I can figure out how to get the Avro plugin working

**Comment by krickert** [comment]
Actually, for now I'm going to try and just use the protobuf instead.  If you're interested in using avro in the future let me know.  I feel like there's better support in general for protobuf, so i'm going to just convert the schemas and use that
