### ISSUE TITLE
Using -1 as Random Port fail

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-grpc#72]
Hi !

I try to run a gRPC test suite so it require a random port.
Documentation state to use in application.yml

```
grpc:
  server:
    port: -1
```

But it lead to 

`Message: port out of range:-1`

Thank you.

**Comment by bidorffOL** [comment]
I believe that the documentation is wrong and should be updated to:
```
grpc:
  server:
    port: ${random.port}
```

**Comment by hrpath** [comment]
Thx @bidorffOL It worked for us
