### ISSUE TITLE
gRPC api discovery by reflection

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-grpc#79]
Hi !

There is documentation here that display how to discover gRPC services without sharing .proto
https://github.com/grpc/grpc/blob/master/doc/server-reflection.md

Java implementation
https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md#enable-server-reflection

It use reflection to expose methods and messages

How to enable reflection in micronaut gRPC ?

Thank you

**Comment by graemerocher** [comment]
You can register it with:

```java
@Factory
class ReflectionFactory {
      @Singleton
       ProtoReflectionService reflectionService() {
              return ProtoReflectionService.newInstance();
       }
}

**Comment by hrpath** [comment]
Thanks !

Does it require a specific import in gradle to make the class visible ?

**Comment by graemerocher** [comment]
See the diff at https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md#enable-server-reflection which explains the dependency to add

**Comment by hrpath** [comment]
ProtoReflectionService.newInstance() return a BindableService so a cast seems to be required
ProtoReflectionService.newInstance() as ProtoReflectionService

**Comment by graemerocher** [comment]
return a `BindableService` in that case

**Comment by hrpath** [comment]
It worked, I can list the services !
Thank

**Comment by mfickett** [comment]
For posterity, the usage that worked in Kotlin was slightly different from the diff linked above:

In my `src/main/kotlin/com/itx/monocle/Application.kt`:

```
package mypkg;

import io.grpc.protobuf.services.ProtoReflectionService;
import io.micronaut.runtime.Micronaut;

fun main(args: Array<String>) {
    Micronaut.build()
        .args(*args)
        .packages("mypkt")
        .singletons(ProtoReflectionService.newInstance())
        .start()
}
```

and in `build.gradle` I added `implementation("io.grpc:grpc-services:${grpcKotlinVersion}")` (where my `gradle.properties` includes `grpcKotlinVersion=0.1.2`.
