### ISSUE TITLE
Regarding gRPC with SSL

### ISSUE THREAD

**Issue by bestmike007** [micronaut-projects/micronaut-grpc#83]
How can I configure gRPC server to use the ssl cert from the file system?

And what if the cert is updated, how can I configure gRPC server to reload and use the latest certificates?

**Comment by graemerocher** [comment]
https://micronaut-projects.github.io/micronaut-grpc/latest/guide/configurationreference.html#io.micronaut.grpc.server.GrpcSslConfiguration

Allows specifying the path to the private cert. As for reload that is beyond the scope of this project, you could maybe configure file watch to watch the path of the cert and have Kubernetes or whatever you are using restart the server when the file changes:

https://docs.micronaut.io/2.0.0.M3/guide/configurationreference.html#io.micronaut.scheduling.io.watch.FileWatchConfiguration
