### ISSUE TITLE
`ClassNotFoundException` when not using discovery

### ISSUE THREAD

**Issue by mcanalesmayo** [micronaut-projects/micronaut-grpc#855]
### Expected Behavior

If user does not want to use discovery (and hence does not have it on the classpath), I'd expect the gRPC server to start without issues.

### Actual Behaviour

The gRPC embedded server cannot start due to the following exception:
```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.grpc.server.GrpcEmbeddedServer] could not be loaded: io/micronaut/discovery/cloud/ComputeInstanceMetadataResolver
	at io.micronaut.context.DefaultBeanContext$BeanDefinitionProducer.getDefinition(DefaultBeanContext.java:4244)
	at io.micronaut.context.DefaultBeanContext.collectBeanCandidates(DefaultBeanContext.java:2160)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2135)
	...
	...
Caused by: java.lang.NoClassDefFoundError: io/micronaut/discovery/cloud/ComputeInstanceMetadataResolver
	at io.micronaut.grpc.server.$GrpcEmbeddedServer$Definition.<clinit>(Unknown Source)
	at io.micronaut.grpc.server.$GrpcEmbeddedServer$Definition$Reference.load(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinitionReference.load(AbstractInitializableBeanDefinitionReference.java:178)
	at io.micronaut.context.DefaultBeanContext$BeanDefinitionProducer.getDefinition(DefaultBeanContext.java:4239)
	... 58 more
Caused by: java.lang.ClassNotFoundException: io.micronaut.discovery.cloud.ComputeInstanceMetadataResolver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 62 more
```

As a workaround, we can add discovery-core to runtime dependencies.

### Steps To Reproduce

Run `./gradlew run`

### Environment Information

JDK21

### Example Application

https://github.com/mcanalesmayo/micronaut-grpc-bug-no-class-def-found

### Version

4.3.4

**Comment by altro3** [comment]
I don't quite understand what your proposal is? What is the benefit of removing the `io.micronaut:micronaut-discovery-core` library from the dependencies?

In general, if you look at the implementation of the GrpcEmbeddedServer server class, you will see that the only way to remove it is to rewrite GrpcEmbeddedServer.

I want to say that the situation now is this: Micronaut provides you with the default implementation of the GrpcEmbeddedServer server, but no one is stopping you from writing your own implementation without using discovery-core. Add an analogue of GrpcEmbeddedServer and mark it as @Primary bean and that’s it, after that everything should work without discovery-core.

But, I think, it is worth adding conditions for GrpcEmbeddedServer, that the default implementation of the server should only use the class `io.micronaut.discovery.ServiceInstance`

@graemerocher I think it's better to change the conditions for `GrpcEmbeddedServer`

From this:
```java
@Requires(classes = io.grpc.ServerBuilder.class)
```

To this:
```java
@Requires(classes = {
    io.grpc.ServerBuilder.class,
    io.micronaut.discovery.ServiceInstance.class
})
```

@graemerocher WDYT?

**Comment by mcanalesmayo** [comment]
@altro3 if I understand correctly, Micronaut discovery is an optional feature, meaning that I, as a user, can opt out
However, the current implementation of `GrpcEmbeddedServer` requires `io.micronaut:micronaut-discovery-core` runtime dependency or it'll fail on startup. It requires me, as a user, to add it to the runtime dependencies, even tho I don't wanna use discovery at all.

**Comment by altro3** [comment]
That's right, it's optional. Hmm, it works. you need to write your own implementation of the EmbeddedServer interface without using discovery. It might make sense to add an Alternative default implementation of the server without using discovery, which would be enabled if there is no `ServiceInstance.class` class in the classpath. And add a condition to GrpcEmbeddedServer for the presence of this class. Then one or another implementation will be enabled, depending on the connected discovery library

**Comment by altro3** [comment]
Well, looking at the code again, I see 2 solutions:

1. Implement the ability to start a service without using classes from discovery, but then you will have to duplicate some classes that are in discovery, for example, events that the service is started or stopped. And the benefit of this is not entirely clear.

2. Change compileOnly to implementation for the `io.micronaut:micronaut-discovery-core` dependency, because this implementation cannot work without this library.

I'm leaning towards the second solution.

@graemerocher @timyates
